export const QUOTES = [
  { text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Will Durant" },
  { text: "Simplicity is prerequisite for reliability.", author: "Edsger W. Dijkstra" },
  { text: "Talk is cheap. Show me the code.", author: "Linus Torvalds" },
  { text: "The best way to predict the future is to invent it.", author: "Alan Kay" },
  { text: "Premature optimization is the root of all evil.", author: "Donald Knuth" },
  { text: "Security is a process, not a product.", author: "Bruce Schneier" },
  { text: "The only way to learn a new programming language is by writing programs in it.", author: "Dennis Ritchie" },
  { text: "Any fool can write code that a computer can understand. Good programmers write code that humans can understand.", author: "Martin Fowler" },
  { text: "Discipline equals freedom.", author: "Jocko Willink" },
  { text: "Make it work, make it right, make it fast.", author: "Kent Beck" },
  { text: "Waste no more time arguing what a good man should be. Be one.", author: "Marcus Aurelius" },
  { text: "We suffer more often in imagination than in reality.", author: "Seneca" },
  { text: "The impediment to action advances action. What stands in the way becomes the way.", author: "Marcus Aurelius" },
  { text: "Amateurs hack systems, professionals hack people.", author: "Bruce Schneier" },
  { text: "Programs must be written for people to read, and only incidentally for machines to execute.", author: "Harold Abelson" },
  { text: "Hard choices, easy life. Easy choices, hard life.", author: "Jerzy Gregorek" },
  { text: "Stay hungry, stay foolish.", author: "Whole Earth Catalog" },
  { text: "Everything should be made as simple as possible, but not simpler.", author: "attributed to Albert Einstein" },
  { text: "The most dangerous phrase in the language is “We've always done it this way.”", author: "Grace Hopper" },
  { text: "First, solve the problem. Then, write the code.", author: "John Johnson" },
  { text: "Knowledge is power.", author: "Francis Bacon" },
];
